<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: star.proto

namespace GPBMetadata;

class Star
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab0010a0a737461722e70726f746f1215676f2e6d6963726f2e73657276" .
            "6963652e7374617222170a0752657175657374120c0a046e616d65180120" .
            "01280922170a08526573706f6e7365120b0a036d73671801200128093251" .
            "0a045374617212490a0443616c6c121e2e676f2e6d6963726f2e73657276" .
            "6963652e737461722e526571756573741a1f2e676f2e6d6963726f2e7365" .
            "72766963652e737461722e526573706f6e73652200620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

